Ruby on Rails capstone project: Budget App
shyusu4/Budget-App pull request #5
Opened 2023-01-19 14:10 UTC by shyusu4

## PR Description

- Created splash screen with links to signup/sign-in using devise gem for authentication
- Created categories page the user can see their name, icon, and the total amount of all the transactions that belongs to that category
- Created a transactions page where the list of transactions is presented, ordered by the most recent
- The user is able to add new categories/transactions
- Created tests for the most important components of the application

2023-01-19 14:45 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @shyusu4, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ All linters passing
✔️ Professional Readme

## Required 
- [ ] Kindly add the video presentation as per the requirements.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 18:23 UTC, ShadyShawkat requested changes
## Hi @shyusu4, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Image](https://c.tenor.com/CWrSBML0hC8AAAAC/little-dinosaur-so-close.gif)

 ## Required Changes ♻️
- [ ] As suggested by the previous reviewer, kindly add a video presentation as per the requirements.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 06:40 UTC, shyusu4 commented
Hi @ShadyShawkat, thank you for the review. I'll make sure to add the video presentation.

2023-01-20 07:01 UTC, Ismailco approved these changes
### Hi @shyusu4, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-01-20 07:01 UTC, Ismailco commented on README.md
> +## 🚀 Live Demo <a name="live-demo"></a>
- [ ] [OPTIONAL] Kindly make sure that your Live app is working properly as for now it returns an error when You try to log in or signup 👇🏼 

![Screenshot_20230120_075830](https://user-images.githubusercontent.com/25227022/213636548-5d262657-9918-47fe-aed5-176dc17d5d4e.png)

2023-01-26 11:03 UTC, merged